export const types = {
    SAVE_GROUP_ITEM_ACTION: 'SAVE_GROUP_ITEM_ACTION',
    DELETE_GROUP_ITEM_ACTION: 'DELETE_GROUP_ITEM_ACTION',
    SEARCH_GROUP_ITEM_ACTION: 'SEARCH_GROUP_ITEM_ACTION',
    SAVE_STUDENT_ITEM_ACTION: 'SAVE_STUDENT_ITEM_ACTION',
    DELETE_STUDENT_ITEM_ACTION: 'DELETE_STUDENT_ITEM_ACTION',
    SEARCH_STUDENT_ITEM_ACTION: 'SEARCH_STUDENT_ITEM_ACTION',
    DELETE_STUDENTS_ITEM_ACTION: 'DELETE_STUDENTS_ITEM_ACTION'
};